### PR TITLE
Nullify all Firebase calls when FirebaseApp is not initialized

### PR DESCRIPTION
**Pull request by luk1337**
# AniTrend Pull Request

Thank you for contributing! Please take a moment to review our [**contributing guidelines**](https://github.com/AniTrend/anitrend-app/blob/master/CONTRIBUTING.md)
to make the process easy and effective for everyone involved.

**Please open an issue** before embarking on any significant pull request, especially those that
add a new library or change existing tests, otherwise you risk spending a lot of time working
on something that might not end up being merged into the project.

Before opening a pull request, please ensure:

- [x] You have followed our [**contributing guidelines**](https://github.com/AniTrend/anitrend-app/blob/master/CONTRIBUTING.md)
- [x] double-check your branch is based on `develop` and targets `develop` 
- [ ] Pull request has tests
- [x] Code is well-commented, linted and follows project conventions
- [x] Documentation is updated (if necessary)
- [x] Description explains the issue/use-case resolved
- [x] I did not commit files that are excluded in the .gitignore file (Happens if you stage files with Android Studio)

## Description
When using a build without Firebase setup, we'd be getting unnecessary log spam when doing certain actions in the app.

## Motivation and Context
See description.

## How Has This Been Tested?
Open app, then close and resume it, observe that following log messages are gone:
```
05-06 22:21:58.336 12272 12272 W System.err: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.mxt.anitrend. Make sure to call FirebaseApp.initializeApp(Context) first.
05-06 22:21:58.336 12272 12272 W System.err: 	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:183)
05-06 22:21:58.336 12272 12272 W System.err: 	at com.google.firebase.crashlytics.FirebaseCrashlytics.getInstance(FirebaseCrashlytics.java:270)
05-06 22:21:58.336 12272 12272 W System.err: 	at com.mxt.anitrend.analytics.AnalyticsLogging$crashlytics$2.invoke(AnalyticsLogging.kt:27)
05-06 22:21:58.336 12272 12272 W System.err: 	at com.mxt.anitrend.analytics.AnalyticsLogging$crashlytics$2.invoke(AnalyticsLogging.kt:16)
05-06 22:21:58.336 12272 12272 W System.err: 	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
05-06 22:21:58.336 12272 12272 W System.err: 	at com.mxt.anitrend.analytics.AnalyticsLogging.getCrashlytics(Unknown Source:2)
05-06 22:21:58.336 12272 12272 W System.err: 	at com.mxt.anitrend.analytics.AnalyticsLogging.setCrashAnalyticUser(AnalyticsLogging.kt:91)
05-06 22:21:58.336 12272 12272 W System.err: 	at com.mxt.anitrend.view.activity.index.MainActivity.setupUserItems(MainActivity.kt:494)
05-06 22:21:58.336 12272 12272 W System.err: 	at com.mxt.anitrend.view.activity.index.MainActivity.updateUI(MainActivity.kt:435)
05-06 22:21:58.336 12272 12272 W System.err: 	at com.mxt.anitrend.view.activity.index.MainActivity.onResume(MainActivity.kt:242)
05-06 22:21:58.336 12272 12272 W System.err: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
05-06 22:21:58.336 12272 12272 W System.err: 	at android.app.Activity.performResume(Activity.java:8135)
05-06 22:21:58.336 12272 12272 W System.err: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4428)
05-06 22:21:58.336 12272 12272 W System.err: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
05-06 22:21:58.336 12272 12272 W System.err: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
05-06 22:21:58.336 12272 12272 W System.err: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
05-06 22:21:58.336 12272 12272 W System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
05-06 22:21:58.336 12272 12272 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
05-06 22:21:58.336 12272 12272 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-06 22:21:58.336 12272 12272 W System.err: 	at android.os.Looper.loop(Looper.java:223)
05-06 22:21:58.336 12272 12272 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
05-06 22:21:58.339 12272 12272 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
05-06 22:21:58.339 12272 12272 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-06 22:21:58.339 12272 12272 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

## Screenshots (if appropriate):
n/a

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

**IMPORTANT**: By submitting a patch, you agree to allow the project
owners to license your work under the terms of the [MIT License](https://github.com/AniTrend/anitrend-app/blob/master/LICENSE.md).

### CODE REVIEW

**Comment by wax911** [comment]
Awesome! Is this happening in production? If I remember correctly the debug build uses a dummy `services.json` file to to allow the application to build.

**Comment by luk1337** [comment]
It doesn't seem to happen on github release builds.

**Comment by luk1337** [comment]
It could also be related to me not having google apps on the phone I actually use to work on AniTrend.

**Comment by wax911** [comment]
> It could also be related to me not having google apps on the phone I actually use to work on AniTrend.

Never thought about that to be honest 😄

**Review by wax911 — APPROVED** [review]

**Pull request merged**
