### PR TITLE
Update Of Links

### PR DESCRIPTION
**Pull request by taichikuji**
Waffle is dead, and i also wanted to add something cool, so there you have it! I added a new icon that shows how many people are online in AniTrend and also has the invite link in it.

### CODE REVIEW

**Comment by wax911** [comment]
Thank you @taichikuji :heart: :hear_no_evil: unfortunatly this was already done in commit: f9680ea1859fb925ca65905abcf8a3bce6a95e25

**Comment by taichikuji** [comment]
I mean, only change is a link, and it hasn't been done before, right? It's literally a button showing how many people are online at the moment, not just the link

**Comment by taichikuji** [comment]
missed the version. it should be 1.4.7 but instead is 1.4.4 just like in the master branch.

**Comment by wax911** [comment]
Looks perfect :100: thank you for the contribution :grinning:

**Pull request merged**
